#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : restructuredtext_lint
Version  : 1.1.3
Release  : 24
URL      : https://files.pythonhosted.org/packages/7e/b5/d28da439210e7f35e4f58f743e2d1fa9c7f34fb5ab9a0532e0bb3a77274a/restructuredtext_lint-1.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/7e/b5/d28da439210e7f35e4f58f743e2d1fa9c7f34fb5ab9a0532e0bb3a77274a/restructuredtext_lint-1.1.3.tar.gz
Summary  : reStructuredText linter
Group    : Development/Tools
License  : Unlicense
Requires: restructuredtext_lint-bin
Requires: restructuredtext_lint-python3
Requires: restructuredtext_lint-license
Requires: restructuredtext_lint-python
Requires: docutils
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=====================

%package bin
Summary: bin components for the restructuredtext_lint package.
Group: Binaries
Requires: restructuredtext_lint-license

%description bin
bin components for the restructuredtext_lint package.


%package license
Summary: license components for the restructuredtext_lint package.
Group: Default

%description license
license components for the restructuredtext_lint package.


%package python
Summary: python components for the restructuredtext_lint package.
Group: Default
Requires: restructuredtext_lint-python3

%description python
python components for the restructuredtext_lint package.


%package python3
Summary: python3 components for the restructuredtext_lint package.
Group: Default
Requires: python3-core

%description python3
python3 components for the restructuredtext_lint package.


%prep
%setup -q -n restructuredtext_lint-1.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532244381
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/restructuredtext_lint
cp UNLICENSE %{buildroot}/usr/share/doc/restructuredtext_lint/UNLICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/restructuredtext-lint
/usr/bin/rst-lint

%files license
%defattr(-,root,root,-)
/usr/share/doc/restructuredtext_lint/UNLICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
