#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : restructuredtext_lint
Version  : 1.2.2
Release  : 27
URL      : https://files.pythonhosted.org/packages/cd/cc/d9e61a7615e723883edd6d9517090d0e73c51933e70794e759eb7fae6ff2/restructuredtext_lint-1.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/cd/cc/d9e61a7615e723883edd6d9517090d0e73c51933e70794e759eb7fae6ff2/restructuredtext_lint-1.2.2.tar.gz
Summary  : reStructuredText linter
Group    : Development/Tools
License  : Unlicense
Requires: restructuredtext_lint-bin = %{version}-%{release}
Requires: restructuredtext_lint-license = %{version}-%{release}
Requires: restructuredtext_lint-python = %{version}-%{release}
Requires: restructuredtext_lint-python3 = %{version}-%{release}
Requires: docutils
BuildRequires : buildreq-distutils3

%description
restructuredtext-lint
=====================
.. image:: https://travis-ci.org/twolfson/restructuredtext-lint.png?branch=master
:target: https://travis-ci.org/twolfson/restructuredtext-lint
:alt: Build Status

%package bin
Summary: bin components for the restructuredtext_lint package.
Group: Binaries
Requires: restructuredtext_lint-license = %{version}-%{release}

%description bin
bin components for the restructuredtext_lint package.


%package license
Summary: license components for the restructuredtext_lint package.
Group: Default

%description license
license components for the restructuredtext_lint package.


%package python
Summary: python components for the restructuredtext_lint package.
Group: Default
Requires: restructuredtext_lint-python3 = %{version}-%{release}

%description python
python components for the restructuredtext_lint package.


%package python3
Summary: python3 components for the restructuredtext_lint package.
Group: Default
Requires: python3-core

%description python3
python3 components for the restructuredtext_lint package.


%prep
%setup -q -n restructuredtext_lint-1.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546788321
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/restructuredtext_lint
cp UNLICENSE %{buildroot}/usr/share/package-licenses/restructuredtext_lint/UNLICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/restructuredtext-lint
/usr/bin/rst-lint

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/restructuredtext_lint/UNLICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
